version: "3.8"

x-default-env: &default-env
  env_file:
    - .env

networks:
  decentracore-network:
    external: true

services:
  hardhat:
    <<: *default-env
    build: .
    container_name: dc_hardhat
    volumes:
      - ./:/app
    command: >
      npx hardhat node
      --hostname 0.0.0.0
      --port 8545
    ports:
      - "8545:8545"
    networks:
      - decentracore-network

  migrate-gas:
    <<: *default-env
    build: .
    container_name: dc_migrate_gas
    volumes:
      - ./:/app
    # Wait for hardhat to be up, then run migrate-gas; skip if default keys
    command: >
      sh -c "
        npx wait-on tcp:hardhat:8545 &&
        npx hardhat migrate-gas --network localhost || echo 'No custom keys detected—skipping migrate-gas';
      "
    environment:
      - PROVIDER_URL=http://hardhat:8545
    depends_on:
      - hardhat
    networks:
      - decentracore-network

  deploy:
    <<: *default-env
    build: .
    container_name: dc_deploy
    volumes:
      - ./:/app
    command: >
      sh -c "
        npx wait-on tcp:hardhat:8545 &&
        npm run deploy &&
        npx hardhat update-frontend-env --network localhost &&
        npx hardhat update-backend-config --network localhost &&
        npm run listen
      "
    environment:
      - PROVIDER_URL=http://hardhat:8545
    depends_on:
      - hardhat
      - migrate-gas
    networks:
      - decentracore-network

  metadata:
    <<: *default-env
    build: .
    container_name: dc_metadata
    volumes:
      - ./:/app
    command: npm run metadata
    environment:
      - METADATA_PORT=3001
      - METADATA_URL=http://localhost:3001
    ports:
      - "3001:3001"
    depends_on:
      - deploy
    networks:
      - decentracore-network

  # listeners:
  #   <<: *default-env
  #   build: .
  #   container_name: dc_listeners
  #   volumes:
  #     - ./:/app
  #   command: >
  #     sh -c "npx wait-on \
  #       'tcp:hardhat:8545' \
  #       'http://metadata:3001' \
  #       'logs/finance/deploy.json' \
  #       'logs/supplyChain/deploy.json' \
  #       'logs/realEstate/deploy.json' \
  #     && npm run listen"
  #   environment:
  #     - PROVIDER_URL=http://hardhat:8545
  #   depends_on:
  #     - metadata
  #     - deploy
  #   networks:
  #     - decentracore-network
